import { useMemo, useState, type DragEvent } from 'react';
import { Brain, Film, FolderOpen, Grid2X2, Import, List, Plus, Search, Trash2 } from 'lucide-react';
import { useEditorStore } from '../../stores/editorStore';
import { useTimelineStore } from '../../stores/timelineStore';
import type { ImportResult, MediaItem } from '../../types/media';

const fmt=(seconds:number)=>{const hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60),secs=Math.floor(seconds%60);return hours?`${hours}:${String(minutes).padStart(2,'0')}:${String(secs).padStart(2,'0')}`:`${String(minutes).padStart(2,'0')}:${String(secs).padStart(2,'0')}`};

export function MediaBrowser({onErrors}:{onErrors:(errors:{path:string;message:string}[])=>void}){
  const [query,setQuery]=useState(''),[dragging,setDragging]=useState(false);
  const {mediaItems,analysisById,selectedMediaId,selectMedia,removeMedia,addMediaBatch,mediaViewMode:view,setMediaViewMode:setView,importProgress}=useEditorStore();
  const addMedia=useTimelineStore(s=>s.addMedia), timeline=useTimelineStore(s=>s.timeline);
  const visible=useMemo(()=>mediaItems.filter(item=>[item.name,analysisById[item.id]?.transcript?.fullText,analysisById[item.id]?.summary?.summary,...(analysisById[item.id]?.summary?.topics||[])].join(' ').toLowerCase().includes(query.toLowerCase())),[mediaItems,analysisById,query]);
  const receive=async(task:()=>Promise<ImportResult>)=>{try{const result=await task();addMediaBatch(result.items);onErrors(result.errors)}catch(error){onErrors([{path:'Import',message:error instanceof Error?error.message:'Import failed'}])}};
  const importDrop=(event:DragEvent)=>{event.preventDefault();setDragging(false);const paths=Array.from(event.dataTransfer.files).map(file=>window.editorAPI.getPathForFile(file)).filter(Boolean);if(paths.length)void receive(()=>window.editorAPI.importPaths(paths))};
  const append=(item:MediaItem)=>{try{addMedia(item,timeline.duration,'V1');selectMedia(item.id);window.dispatchEvent(new CustomEvent('savana:preview-mode',{detail:'program'}))}catch(error){onErrors([{path:item.name,message:error instanceof Error?error.message:'Could not add clip to timeline'}])}};
  const beginDrag=(event:DragEvent<HTMLElement>,item:MediaItem)=>{event.dataTransfer.effectAllowed='copy';event.dataTransfer.setData('application/x-savana-media',item.id);event.dataTransfer.setData('text/plain',item.name)};
  return <section className={`media-browser ${dragging?'is-dragging':''}`} onDragEnter={event=>{if(event.dataTransfer.types.includes('Files')){event.preventDefault();setDragging(true)}}} onDragOver={event=>{if(event.dataTransfer.types.includes('Files'))event.preventDefault()}} onDragLeave={event=>{if(event.currentTarget===event.target)setDragging(false)}} onDrop={importDrop}>
    <div className="panel-title"><span>Project media</span><span className="count">{mediaItems.length}</span><button className="analyze-all" disabled={!mediaItems.length} onClick={()=>void window.editorAPI.analyzeAll()}><Brain size={12}/>Analyze all</button></div>
    <div className="import-actions"><button className="primary" disabled={importProgress.active} onClick={()=>void receive(window.editorAPI.importMedia)}><Import size={14}/>Import media</button><button disabled={importProgress.active} onClick={()=>void receive(window.editorAPI.importFolder)}><FolderOpen size={15}/>Import folder</button></div>
    <div className="browser-tools"><label><Search size={13}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search media"/></label><div className="view-toggle"><button className={view==='grid'?'active':''} title="Grid view" onClick={()=>setView('grid')}><Grid2X2 size={14}/></button><button className={view==='list'?'active':''} title="List view" onClick={()=>setView('list')}><List size={15}/></button></div></div>
    {importProgress.active&&<div className="import-progress">{importProgress.message}</div>}
    {!visible.length?<div className="drop-empty"><Film size={29}/><strong>{dragging?'Drop to import':query?'No matching media':'Your media will appear here'}</strong><span>{query?'Try another search':'Import files or drag them here'}</span></div>:<div className={`media-grid ${view}`}>{visible.map(item=><article key={item.id} draggable={item.status!=='error'} onDragStart={event=>beginDrag(event,item)} className={`${selectedMediaId===item.id?'selected':''} ${item.status==='error'?'media-error':''}`} onClick={()=>item.status!=='error'&&selectMedia(item.id)} onDoubleClick={()=>item.status!=='error'&&append(item)}><div className="thumb">{item.thumbnailPath?<img src={window.editorAPI.getMediaUrl(item.id,'thumbnail')} alt=""/>:<Film/>}<span>{fmt(item.duration)}</span><button className="remove" title="Remove media" onClick={event=>{event.stopPropagation();removeMedia(item.id)}}><Trash2 size={12}/></button></div><div className="media-copy"><strong>{item.name}</strong><small>{item.error||`${item.width}×${item.height} · ${item.fps.toFixed(2)} FPS`}</small><i>{item.analysisStatus||'not analyzed'}</i><button className="add-to-timeline" disabled={item.status==='error'} onClick={event=>{event.stopPropagation();append(item)}}><Plus size={12}/>Add to timeline</button></div></article>)}</div>}
    <div className="media-help">Drag a clip to a video track, double-click it, or use Add to timeline.</div>
  </section>;
}
