import { create } from 'zustand';
import type { CaptionItem, CreativeState, EffectInstance, OverlayItem, TitleItem, TransformSettings } from '../types/creative';
import { registryItem } from '../rendering/registries';
import { useTimelineStore } from './timelineStore';
import { validateTimeline } from '../services/timelineValidation';
const initial:CreativeState={overlays:[],captions:[],titles:[],favoriteIds:JSON.parse(localStorage.getItem('savana:favorites')||'[]'),recentIds:JSON.parse(localStorage.getItem('savana:recent')||'[]'),previewQuality:'preview'};
const defaults=(id:string)=>Object.fromEntries((registryItem(id)?.parameters||[]).map(parameter=>[parameter.id,parameter.defaultValue]));
const editClip=(change:(clip:import('../types/timeline').TimelineClip)=>void)=>{const store=useTimelineStore.getState(),next=structuredClone(store.timeline),clip=next.tracks.flatMap(track=>track.clips).find(item=>item.id===store.selectedClipIds[0]);if(!clip)return;change(clip);validateTimeline(next);useTimelineStore.setState({timeline:next,past:[...store.past.slice(-49),structuredClone(store.timeline)],future:[]})};
interface Store extends CreativeState{hydrate:(value?:Partial<CreativeState>)=>void;addEffect:(id:string)=>void;updateEffect:(id:string,patch:Partial<EffectInstance>)=>void;removeEffect:(id:string)=>void;setTransform:(patch:Partial<TransformSettings>)=>void;setTransition:(id:string,duration?:number)=>void;removeTransition:()=>void;addOverlay:(id:string,start?:number)=>void;addCaption:(item:CaptionItem)=>void;addTitle:(item:TitleItem)=>void;toggleFavorite:(id:string)=>void;useItem:(id:string)=>void;setPreviewQuality:(value:CreativeState['previewQuality'])=>void}
export const useCreativeStore=create<Store>((set,get)=>({...initial,hydrate:value=>set({...initial,...value,favoriteIds:value?.favoriteIds||initial.favoriteIds,recentIds:value?.recentIds||initial.recentIds}),
 addEffect:effectId=>{editClip(clip=>{if(!registryItem(effectId))throw new Error(`Unknown effect: ${effectId}`);clip.effects=[...(clip.effects||[]),{id:crypto.randomUUID(),effectId,enabled:true,parameters:defaults(effectId),start:0,duration:clip.duration,keyframes:{}}]});get().useItem(effectId)},updateEffect:(id,patch)=>editClip(clip=>{clip.effects=(clip.effects||[]).map(effect=>effect.id===id?{...effect,...patch}:effect)}),removeEffect:id=>editClip(clip=>{clip.effects=(clip.effects||[]).filter(effect=>effect.id!==id)}),
 setTransform:patch=>editClip(clip=>{clip.transform={positionX:0,positionY:0,scale:100,rotation:0,anchorX:50,anchorY:50,opacity:100,...clip.transform,...patch}}),setTransition:(transitionId,duration=.5)=>{editClip(clip=>{if(!registryItem(transitionId))throw new Error(`Unknown transition: ${transitionId}`);clip.transitionOut=transitionId==='cut'?undefined:{id:crypto.randomUUID(),transitionId,duration,parameters:defaults(transitionId)}});get().useItem(transitionId)},removeTransition:()=>editClip(clip=>{clip.transitionOut=undefined}),
 addOverlay:(overlayId,start)=>{if(!registryItem(overlayId))throw new Error(`Unknown overlay: ${overlayId}`);const overlay:OverlayItem={id:crypto.randomUUID(),overlayId,timelineStart:start??useTimelineStore.getState().timeline.playhead,duration:2,parameters:defaults(overlayId),blendMode:'screen'};set(state=>({overlays:[...state.overlays,overlay]}));get().useItem(overlayId)},addCaption:item=>set(state=>({captions:[...state.captions,item]})),addTitle:item=>set(state=>({titles:[...state.titles,item]})),
 toggleFavorite:id=>set(state=>{const favoriteIds=state.favoriteIds.includes(id)?state.favoriteIds.filter(value=>value!==id):[...state.favoriteIds,id];localStorage.setItem('savana:favorites',JSON.stringify(favoriteIds));return{favoriteIds}}),useItem:id=>set(state=>{const recentIds=[id,...state.recentIds.filter(value=>value!==id)].slice(0,20);localStorage.setItem('savana:recent',JSON.stringify(recentIds));return{recentIds}}),setPreviewQuality:previewQuality=>set({previewQuality})}));
