import { create } from 'zustand';
import type { EditPlan, TimelineClip, TimelineModel, TimelineTrack, TimelineTrackType } from '../types/timeline';
import type { MediaItem } from '../types/media';
import { clipAtSourceRange, validateTimeline } from '../services/timelineValidation';
import { snapTimeToFrame } from '../utils/time';
import { applyTimelinePatch, type TimelinePatch } from '../services/timelinePatch';
import { useTransportStore } from './transportStore';

const baseTracks = (): TimelineTrack[] => [{id:'V2',type:'video',name:'V2',locked:false,visible:true,clips:[]},{id:'V1',type:'video',name:'V1',locked:false,visible:true,clips:[]},{id:'A1',type:'audio',name:'A1',locked:false,muted:false,clips:[]}];
const empty = (): TimelineModel => ({duration:0,fps:30,tracks:baseTracks(),playhead:0});
const calculateDuration = (timeline: TimelineModel) => Math.max(0,...timeline.tracks.flatMap(track=>track.clips.map(clip=>clip.timelineStart+clip.duration)));

interface State {
 timeline:TimelineModel; selectedClipIds:string[]; past:TimelineModel[]; future:TimelineModel[]; ripple:boolean; snapping:boolean; snapGuide?:number; clipboard:TimelineClip[];
 hydrate:(timeline?:TimelineModel)=>void; applyPatch:(patch:TimelinePatch,media:MediaItem[])=>void; setPlayhead:(time:number)=>void; addTrack:(type:TimelineTrackType)=>void;deleteTrack:(id:string)=>void;renameTrack:(id:string,name:string)=>void;toggleTrackLock:(id:string)=>void;toggleTrackVisibility:(id:string)=>void;toggleTrackMute:(id:string)=>void;selectClip:(id?:string,additive?:boolean)=>void; addMedia:(media:MediaItem,start:number,trackId?:string,sourceIn?:number,sourceOut?:number)=>void; applyPlan:(plan:EditPlan,media:MediaItem[])=>void; moveClip:(id:string,start:number,trackId:string,scale?:number)=>void; trimClip:(id:string,edge:'left'|'right',delta:number,max:number,scale?:number)=>void; splitSelected:()=>void; deleteSelected:(ripple?:boolean)=>void; removeSourceRange:(mediaId:string,start:number,end:number,ripple:boolean)=>void; copy:()=>void; paste:()=>void; undo:()=>void; redo:()=>void; setRipple:(value:boolean)=>void; toggleSnapping:()=>void; setSnapGuide:(value?:number)=>void;
}

export const useTimelineStore = create<State>((set,get) => {
 const commit = (change:(timeline:TimelineModel)=>void) => set(state => {
   const proposed=structuredClone(state.timeline); change(proposed); proposed.duration=calculateDuration(proposed); validateTimeline(proposed);
   return {timeline:proposed,past:[...state.past.slice(-49),structuredClone(state.timeline)],future:[],snapGuide:undefined};
 });
 const findLinked=(timeline:TimelineModel,clip:TimelineClip)=>timeline.tracks.flatMap(track=>track.clips).find(candidate=>candidate.id===clip.linkedClipId);
 const snap=(time:number,scale=48,exclude?:string)=>{
   const state=get(); if(!state.snapping)return snapTimeToFrame(Math.max(0,time),state.timeline.fps);
   const targets=[0,useTransportStore.getState().currentTime,...state.timeline.tracks.flatMap(track=>track.clips.filter(clip=>clip.id!==exclude).flatMap(clip=>[clip.timelineStart,clip.timelineStart+clip.duration]))];
   const tolerance=8/scale; let best=time,distance=tolerance; for(const target of targets){const next=Math.abs(target-time);if(next<distance){best=target;distance=next}}
   set({snapGuide:best!==time?best:undefined}); return snapTimeToFrame(Math.max(0,best),state.timeline.fps);
 };
 return {
  timeline:empty(),selectedClipIds:[],past:[],future:[],ripple:false,snapping:true,clipboard:[],
  hydrate:timeline=>{const value=timeline||empty();try{validateTimeline(value);set({timeline:value,past:[],future:[],selectedClipIds:[]})}catch{set({timeline:empty(),past:[],future:[],selectedClipIds:[]})}},
  applyPatch:(patch,media)=>set(state=>({timeline:applyTimelinePatch(state.timeline,patch,media),past:[...state.past.slice(-49),structuredClone(state.timeline)],future:[],selectedClipIds:[]})),
  setPlayhead:playhead=>useTransportStore.getState().setCurrentTime(playhead,get().timeline.fps),
  addTrack:type=>commit(timeline=>{const prefix={video:'V',audio:'A',overlay:'O',text:'T',graphics:'G',adjustment:'ADJ'}[type],numbers=timeline.tracks.filter(track=>track.type===type).map(track=>Number(track.id.replace(/\D/g,''))||0),id=`${prefix}${Math.max(0,...numbers)+1}`,track:TimelineTrack={id,type,name:id,locked:false,visible:type==='audio'?undefined:true,muted:type==='audio'?false:undefined,solo:type==='audio'?false:undefined,volume:type==='audio'?1:undefined,height:52,clips:[]};const firstAudio=timeline.tracks.findIndex(item=>item.type==='audio');if(type==='audio'||firstAudio<0)timeline.tracks.push(track);else timeline.tracks.splice(0,0,track)}),
  deleteTrack:id=>commit(timeline=>{const track=timeline.tracks.find(item=>item.id===id);if(!track)throw new Error('Track not found.');if(track.clips.length)throw new Error('Delete or move clips before deleting this track.');if(timeline.tracks.filter(item=>item.type===track.type).length<=1&&['video','audio'].includes(track.type))throw new Error(`A project must keep at least one ${track.type} track.`);timeline.tracks=timeline.tracks.filter(item=>item.id!==id)}),
  renameTrack:(id,name)=>commit(timeline=>{const track=timeline.tracks.find(item=>item.id===id);if(track)track.name=String(name).trim().slice(0,40)||track.id}),
  toggleTrackLock:id=>commit(timeline=>{const track=timeline.tracks.find(item=>item.id===id);if(track)track.locked=!track.locked}),
  toggleTrackVisibility:id=>commit(timeline=>{const track=timeline.tracks.find(item=>item.id===id);if(track)track.visible=track.visible===false}),
  toggleTrackMute:id=>commit(timeline=>{const track=timeline.tracks.find(item=>item.id===id);if(track&&track.type==='audio')track.muted=!track.muted}),
  selectClip:(id,additive=false)=>set(state=>({selectedClipIds:id?(additive?[...new Set([...state.selectedClipIds,id])]:[id]):[]})),
  addMedia:(media,start,trackId='V1',sourceIn=0,sourceOut=media.duration)=>{const selected:string[]=[];commit(timeline=>{const target=timeline.tracks.find(track=>track.id===trackId);if(!target)throw new Error(`Track ${trackId} does not exist.`);if(target.type!=='video')throw new Error('Video media must be placed on a video track.');const id=crypto.randomUUID(),firstVideo=!timeline.tracks.some(track=>track.type==='video'&&track.clips.length),timelineStart=firstVideo?0:snap(start),clip:TimelineClip={id,mediaId:media.id,trackId,timelineStart,sourceIn,sourceOut,duration:sourceOut-sourceIn,name:media.name,color:'#347d69'};target.clips.push(clip);selected.push(id);if(media.hasAudio&&trackId==='V1'){const audioId=crypto.randomUUID();clip.linkedClipId=audioId;timeline.tracks.find(track=>track.id==='A1')?.clips.push({...clip,id:audioId,trackId:'A1',linkedClipId:id,color:'#5b6685'})}});set({selectedClipIds:selected})},
  applyPlan:(plan,media)=>commit(timeline=>{timeline.tracks=baseTracks();for(const item of plan.timeline){if(item.type!=='video'||!item.sourceMediaId)continue;const source=media.find(candidate=>candidate.id===item.sourceMediaId);if(!source)continue;const id=crypto.randomUUID(),clip:TimelineClip={id,mediaId:source.id,trackId:item.trackId,timelineStart:item.timelineStart,sourceIn:item.sourceStart||0,sourceOut:item.sourceEnd||item.duration,duration:item.duration,name:source.name,role:item.role,color:item.role==='broll'?'#6b527e':'#347d69'};timeline.tracks.find(track=>track.id===item.trackId)?.clips.push(clip);if(source.hasAudio&&item.trackId==='V1'){const audioId=crypto.randomUUID();clip.linkedClipId=audioId;timeline.tracks.find(track=>track.id==='A1')?.clips.push({...clip,id:audioId,trackId:'A1',linkedClipId:id,color:'#5b6685'})}}}),
  moveClip:(id,start,trackId,scale=48)=>commit(timeline=>{for(const track of timeline.tracks){const index=track.clips.findIndex(clip=>clip.id===id);if(index<0)continue;const[clip]=track.clips.splice(index,1),next=snap(start,scale,id);clip.timelineStart=next;clip.trackId=trackId;timeline.tracks.find(candidate=>candidate.id===trackId)?.clips.push(clip);const pair=findLinked(timeline,clip);if(pair)pair.timelineStart=next;break}}),
  trimClip:(id,edge,delta,max,scale=48)=>commit(timeline=>{const clip=timeline.tracks.flatMap(track=>track.clips).find(candidate=>candidate.id===id);if(!clip)return;const oldEnd=clip.timelineStart+clip.duration;if(edge==='left'){const next=snap(clip.timelineStart+delta,scale,id),amount=Math.max(-clip.sourceIn,Math.min(next-clip.timelineStart,clip.duration-.1));clip.timelineStart+=amount;clip.sourceIn+=amount}else{const next=snap(oldEnd+delta,scale,id);clip.sourceOut=Math.max(clip.sourceIn+.1,Math.min(max,clip.sourceOut+(next-oldEnd)))}clip.duration=clip.sourceOut-clip.sourceIn;const pair=findLinked(timeline,clip);if(pair)Object.assign(pair,{timelineStart:clip.timelineStart,sourceIn:clip.sourceIn,sourceOut:clip.sourceOut,duration:clip.duration})}),
  splitSelected:()=>commit(timeline=>{const playhead=useTransportStore.getState().currentTime,processed=new Set<string>();for(const id of get().selectedClipIds){if(processed.has(id))continue;const clip=timeline.tracks.flatMap(track=>track.clips).find(candidate=>candidate.id===id);if(!clip||playhead<=clip.timelineStart+.05||playhead>=clip.timelineStart+clip.duration-.05)continue;for(const current of[clip,findLinked(timeline,clip)].filter(Boolean)as TimelineClip[]){processed.add(current.id);const d=playhead-current.timelineStart;timeline.tracks.find(track=>track.id===current.trackId)?.clips.push({...current,id:crypto.randomUUID(),timelineStart:playhead,sourceIn:current.sourceIn+d,duration:current.duration-d,linkedClipId:undefined});current.sourceOut=current.sourceIn+d;current.duration=d;current.linkedClipId=undefined}}}),
  deleteSelected:force=>{const ids=new Set(get().selectedClipIds);commit(timeline=>{for(const clip of timeline.tracks.flatMap(track=>track.clips).filter(candidate=>ids.has(candidate.id)))if(clip.linkedClipId)ids.add(clip.linkedClipId);for(const track of timeline.tracks){const removed=track.clips.filter(clip=>ids.has(clip.id));track.clips=track.clips.filter(clip=>!ids.has(clip.id));if(force??get().ripple)for(const gone of removed)for(const clip of track.clips)if(clip.timelineStart>=gone.timelineStart+gone.duration-.001)clip.timelineStart-=gone.duration}});set({selectedClipIds:[]})},
  removeSourceRange:(mediaId,start,end,ripple)=>commit(timeline=>{for(const track of timeline.tracks){for(const clip of[...track.clips].filter(candidate=>candidate.mediaId===mediaId)){const mapped=clipAtSourceRange(clip,start,end);if(!mapped)continue;track.clips=track.clips.filter(candidate=>candidate.id!==clip.id);const left=mapped.sourceStart-clip.sourceIn,right=clip.sourceOut-mapped.sourceEnd;if(left>=.1)track.clips.push({...clip,id:crypto.randomUUID(),sourceOut:mapped.sourceStart,duration:left,linkedClipId:undefined});if(right>=.1)track.clips.push({...clip,id:crypto.randomUUID(),timelineStart:mapped.timelineEnd,sourceIn:mapped.sourceEnd,duration:right,linkedClipId:undefined});if(ripple)for(const other of track.clips)if(other.timelineStart>=mapped.timelineEnd-.001)other.timelineStart-=mapped.timelineEnd-mapped.timelineStart}}}),
  copy:()=>set(state=>({clipboard:state.timeline.tracks.flatMap(track=>track.clips).filter(clip=>state.selectedClipIds.includes(clip.id)).map(clip=>structuredClone(clip))})),
  paste:()=>{const clips=get().clipboard;if(!clips.length)return;const minimum=Math.min(...clips.map(clip=>clip.timelineStart)),playhead=useTransportStore.getState().currentTime;commit(timeline=>{for(const clip of clips){const copy={...clip,id:crypto.randomUUID(),linkedClipId:undefined,timelineStart:playhead+(clip.timelineStart-minimum)};timeline.tracks.find(track=>track.id===copy.trackId)?.clips.push(copy)}})},
  undo:()=>set(state=>{const previous=state.past.at(-1);return previous?{timeline:previous,past:state.past.slice(0,-1),future:[structuredClone(state.timeline),...state.future],selectedClipIds:[]}:state}),
  redo:()=>set(state=>{const next=state.future[0];return next?{timeline:next,past:[...state.past,structuredClone(state.timeline)],future:state.future.slice(1),selectedClipIds:[]}:state}),
  setRipple:ripple=>set({ripple}),toggleSnapping:()=>set(state=>({snapping:!state.snapping,snapGuide:undefined})),setSnapGuide:snapGuide=>set({snapGuide})
 };
});
