import { useEffect, useMemo, useRef, useState } from 'react';
import { Expand, Pause, Play, SkipBack, SkipForward, Volume2, VolumeX } from 'lucide-react';
import { useEditorStore } from '../../stores/editorStore';
import { useTimelineStore } from '../../stores/timelineStore';
import { useTransportStore } from '../../stores/transportStore';
import { resolveTimeline } from '../../services/timelineResolver';

const formatTime=(value:number,fps=30)=>{const safe=Math.max(0,value||0),hours=Math.floor(safe/3600),minutes=Math.floor(safe%3600/60),seconds=Math.floor(safe%60),frames=Math.floor((safe%1)*fps);return `${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}:${String(frames).padStart(2,'0')}`};

export function PreviewPanel(){
  const [mode,setMode]=useState<'source'|'program'>('source'),[sourceTime,setSourceTime]=useState(0),[volume,setVolume]=useState(1),[previewError,setPreviewError]=useState('');
  const selected=useEditorStore(s=>s.mediaItems.find(item=>item.id===s.selectedMediaId)),media=useEditorStore(s=>s.mediaItems),timeline=useTimelineStore(s=>s.timeline);
  const {currentTime,playing,playbackRate,loop,setCurrentTime,setPlaying,togglePlaying}=useTransportStore();
  const videoRef=useRef<HTMLVideoElement>(null),viewerRef=useRef<HTMLDivElement>(null),clockRef=useRef<number>(),lastRef=useRef<number>(),currentTimeRef=useRef(currentTime);currentTimeRef.current=currentTime;
  const resolved=useMemo(()=>resolveTimeline(timeline,media,currentTime),[timeline,media,currentTime]),active=resolved.topVideo;
  const source=mode==='program'?active?.media:selected,targetSourceTime=mode==='program'?active?.sourceTime:sourceTime,duration=mode==='program'?timeline.duration:selected?.duration||0,fps=timeline.fps||30;

  useEffect(()=>{const video=videoRef.current;if(!video)return;video.volume=volume;video.playbackRate=playbackRate},[volume,playbackRate,source?.id]);
  useEffect(()=>{if(mode==='source'){setPlaying(false);setSourceTime(0)}},[selected?.id,mode,setPlaying]);
  useEffect(()=>{const video=videoRef.current;if(!video||!source)return;const sync=()=>{video.currentTime=Math.max(0,targetSourceTime||0);video.volume=volume;video.playbackRate=playbackRate;if(playing)void video.play().catch(error=>{setPlaying(false);setPreviewError(error.message)})};if(video.readyState>=1)sync();else video.addEventListener('loadedmetadata',sync,{once:true});return()=>video.removeEventListener('loadedmetadata',sync)},[source?.id,mode]);
  useEffect(()=>{if(mode!=='program'||!videoRef.current||!active)return;const drift=Math.abs(videoRef.current.currentTime-active.sourceTime);if(!playing||drift>.2)videoRef.current.currentTime=Math.max(0,active.sourceTime)},[mode,currentTime,active?.clip.id,active?.sourceTime,playing]);
  useEffect(()=>{const video=videoRef.current;if(!video)return;if(playing&&source)void video.play().catch(error=>{setPlaying(false);setPreviewError(error.message)});else video.pause()},[playing,source?.id,setPlaying]);
  useEffect(()=>{if(mode!=='program'||!playing){if(clockRef.current)cancelAnimationFrame(clockRef.current);lastRef.current=undefined;return}const tick=(now:number)=>{const last=lastRef.current??now,next=currentTimeRef.current+(now-last)/1000*playbackRate;lastRef.current=now;if(next>=timeline.duration){if(loop){currentTimeRef.current=0;setCurrentTime(0,timeline.fps)}else{currentTimeRef.current=timeline.duration;setCurrentTime(timeline.duration,timeline.fps);setPlaying(false);return}}else{currentTimeRef.current=next;setCurrentTime(next,timeline.fps)}clockRef.current=requestAnimationFrame(tick)};clockRef.current=requestAnimationFrame(tick);return()=>{if(clockRef.current)cancelAnimationFrame(clockRef.current);lastRef.current=undefined}},[mode,playing,playbackRate,loop,timeline.duration,timeline.fps,setCurrentTime,setPlaying]);
  useEffect(()=>{const modeListener=((event:CustomEvent<'source'|'program'>)=>setMode(event.detail))as EventListener,seek=((event:CustomEvent<number>)=>{if(mode==='source'){setSourceTime(event.detail);if(videoRef.current)videoRef.current.currentTime=event.detail}else setCurrentTime(event.detail,timeline.fps)})as EventListener,full=()=>void viewerRef.current?.requestFullscreen();window.addEventListener('savana:preview-mode',modeListener);window.addEventListener('savana:seek',seek);window.addEventListener('savana:fullscreen-preview',full);return()=>{window.removeEventListener('savana:preview-mode',modeListener);window.removeEventListener('savana:seek',seek);window.removeEventListener('savana:fullscreen-preview',full)}},[mode,timeline.fps,setCurrentTime]);
  const scrub=(next:number)=>{const bounded=Math.max(0,Math.min(duration,next));if(mode==='program')setCurrentTime(bounded,timeline.fps);else{setSourceTime(bounded);if(videoRef.current)videoRef.current.currentTime=bounded}};
  const seekFrame=(direction:number)=>scrub((mode==='program'?currentTime:sourceTime)+direction/fps),time=mode==='program'?currentTime:sourceTime;
  const toggle=()=>{if(mode==='program')togglePlaying();else{const video=videoRef.current;if(!video)return;if(video.paused){setPlaying(true);void video.play().catch(error=>setPreviewError(error.message))}else{video.pause();setPlaying(false)}}};
  return <section className="preview-panel"><div className="preview-header"><div className="preview-modes"><button className={mode==='source'?'active':''} onClick={()=>setMode('source')}>Source</button><button className={mode==='program'?'active':''} onClick={()=>setMode('program')}>Program</button></div><strong>{mode==='program'?'Interactive Timeline':selected?.name||'No clip selected'}</strong>{mode==='program'&&<small>Low-latency preview</small>}<button onClick={()=>void viewerRef.current?.requestFullscreen()} disabled={!source}><Expand size={14}/></button></div><div className="viewer" ref={viewerRef}>{source?<video key={source.id} ref={videoRef} src={window.editorAPI.getMediaUrl(source.id)} preload="auto" playsInline onLoadedMetadata={e=>{e.currentTarget.currentTime=Math.max(0,targetSourceTime||0);setPreviewError('')}} onTimeUpdate={e=>{if(mode==='source'){setSourceTime(e.currentTarget.currentTime);window.dispatchEvent(new CustomEvent('savana:time',{detail:e.currentTarget.currentTime}))}}} onPlay={()=>setPlaying(true)} onPause={()=>{if(mode==='source')setPlaying(false)}} onError={()=>setPreviewError('Preview decode failed. Reimport this clip to create a compatibility proxy.')}/>:<div className="canvas-empty"><Play size={24}/><span>{mode==='program'?'Place a clip at the playhead':'Select media to preview'}</span></div>}{previewError&&<div className="preview-error">{previewError}</div>}</div><input className="scrubber" type="range" min="0" max={Math.max(.01,duration)} step={1/fps} value={Math.min(time,duration)} onChange={e=>scrub(Number(e.target.value))}/><div className="transport"><span className="timecode">{formatTime(time,fps)}</span><div className="transport-center"><button title="Previous frame" onClick={()=>seekFrame(-1)} disabled={!duration}><SkipBack size={15}/></button><button className="play" title="Play / Pause (Space)" onClick={toggle} disabled={!duration}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><button title="Next frame" onClick={()=>seekFrame(1)} disabled={!duration}><SkipForward size={15}/></button></div><div className="transport-right"><span>{formatTime(duration,fps)}</span><button title="Mute" onClick={()=>setVolume(value=>value?0:1)}>{volume?<Volume2 size={16}/>:<VolumeX size={16}/>}</button><button title="Fullscreen" onClick={()=>void viewerRef.current?.requestFullscreen()} disabled={!duration}><Expand size={15}/></button></div></div></section>;
}
