const {app,dialog,ipcMain}=require('electron');
const fs=require('node:fs/promises');const path=require('node:path');const crypto=require('node:crypto');
const {engineStatus,analyze,thumbnail,salvage,previewProxy}=require('../services/ffmpeg.cjs');const project=require('../services/project.cjs');
const EXTENSIONS=new Set(['.mp4','.mov','.mkv','.avi','.webm','.m4v','.qt','.3gp','.3g2','.mts','.m2ts','.ts','.mpg','.mpeg','.vob','.wmv','.asf','.flv','.ogv','.mxf','.hevc','.h265']);
const registry=new Map(),pathRegistry=new Map();
const supported=file=>EXTENSIONS.has(path.extname(file).toLowerCase());
const normalize=file=>process.platform==='win32'?path.resolve(file).toLocaleLowerCase():path.resolve(file);
function valid(value){if(typeof value!=='string'||!path.isAbsolute(value))throw new Error('A valid absolute path is required.');return path.resolve(value)}
function registerItem(item){registry.set(`video:${item.id}`,item.playbackPath||item.path);pathRegistry.set(normalize(item.path),item);if(item.thumbnailPath)registry.set(`thumbnail:${item.id}`,item.thumbnailPath)}
function resolveMedia(kind,id){return registry.get(`${kind}:${id}`)}
function registerAsset(kind,id,file){registry.set(`${kind}:${id}`,file)}function getItem(id){return[...pathRegistry.values()].find(item=>item.id===id)}function getItems(){return[...pathRegistry.values()]}
async function walk(target,errors){let stat;try{stat=await fs.stat(target)}catch(error){errors.push({path:target,message:`Cannot access file: ${error.message}`});return[]}if(stat.isFile())return supported(target)?[path.resolve(target)]:[];if(!stat.isDirectory())return[];let entries;try{entries=await fs.readdir(target,{withFileTypes:true})}catch(error){errors.push({path:target,message:`Cannot read folder: ${error.message}`});return[]}const found=[];for(const entry of entries){const child=path.join(target,entry.name);if(entry.isDirectory())found.push(...await walk(child,errors));else if(entry.isFile()&&supported(child))found.push(child)}return found}
async function processOne(file,errors){const existing=pathRegistry.get(normalize(file));if(existing)return existing;const thumbs=path.join(app.getPath('cache'),'SavanaEdit','thumbnails'),recovery=path.join(app.getPath('cache'),'SavanaEdit','recovery'),proxies=path.join(app.getPath('cache'),'SavanaEdit','proxies');let item;try{item=await analyze(file)}catch(original){try{const recovered=await salvage(file,recovery);item=await analyze(recovered);item={...item,id:crypto.createHash('sha256').update(normalize(file)).digest('hex').slice(0,32),name:path.basename(file),path:path.resolve(file),playbackPath:recovered,recovered:true,error:'A cached recovery copy is being used because the source container is damaged.'}}catch{errors.push({path:file,message:original.message||'The video could not be decoded or recovered.'});return null}}if(['hevc','h265','prores','dnxhd','mpeg2video'].includes(String(item.videoCodec).toLowerCase())){try{item.playbackPath=await previewProxy(item.playbackPath||item.path,proxies,item.id)}catch(error){errors.push({path:file,message:`Compatibility preview could not be created: ${error.message}`})}}try{item.thumbnailPath=await thumbnail(item.playbackPath||item.path,item.duration,thumbs,item.id)}catch(error){errors.push({path:file,message:`Thumbnail unavailable: ${error.message}`})}registerItem(item);return item}
async function processTargets(targets,event){const errors=[],all=[];for(const target of targets)all.push(...await walk(valid(target),errors));const files=[...new Map(all.map(file=>[normalize(file),file])).values()],items=new Array(files.length);let cursor=0,done=0;const send=message=>event.sender.send('media:progress',{active:done<files.length,current:done,total:files.length,message});send(files.length?`Preparing ${files.length} media file${files.length===1?'':'s'}…`:'Ready');async function worker(){while(true){const index=cursor++;if(index>=files.length)return;send(`Analyzing ${index+1} of ${files.length}: ${path.basename(files[index])}`);items[index]=await processOne(files[index],errors);done++;send(done<files.length?`Processed ${done} of ${files.length}`:'Ready')}}await Promise.all(Array.from({length:Math.min(2,files.length)},worker));event.sender.send('media:progress',{active:false,current:done,total:files.length,message:'Ready'});return{items:items.filter(Boolean),errors}}
function registerMediaIpc(){
 ipcMain.handle('media:engine-status',()=>engineStatus());
 ipcMain.handle('media:import-files',async event=>{const result=await dialog.showOpenDialog({properties:['openFile','multiSelections'],filters:[{name:'Video media',extensions:[...EXTENSIONS].map(value=>value.slice(1))},{name:'All files',extensions:['*']}]});return result.canceled?{items:[],errors:[],canceled:true}:processTargets(result.filePaths,event)});
 ipcMain.handle('media:import-folder',async event=>{const result=await dialog.showOpenDialog({properties:['openDirectory']});return result.canceled?{items:[],errors:[],canceled:true}:processTargets(result.filePaths,event)});
 ipcMain.handle('media:import-paths',(event,paths)=>processTargets(Array.isArray(paths)?paths:[],event));
 ipcMain.handle('project:load',async()=>{const loaded=await project.load(app);for(const item of loaded.mediaItems||[])registerItem(item);return loaded});
 ipcMain.handle('project:open',async()=>{const result=await dialog.showOpenDialog({properties:['openFile'],filters:[{name:'SavanaEdit Project',extensions:['savana','json']}]});if(result.canceled)return null;const loaded=await project.read(result.filePaths[0]);for(const item of loaded.mediaItems||[])registerItem(item);return loaded});
 ipcMain.handle('project:save-as',async(_event,value)=>{const result=await dialog.showSaveDialog({defaultPath:`${String(value?.projectName||'Untitled Project').replace(/[<>:"/\\|?*]/g,'-')}.savana`,filters:[{name:'SavanaEdit Project',extensions:['savana']}]});if(result.canceled||!result.filePath)return null;await project.saveTo(result.filePath,value);return result.filePath});
 ipcMain.handle('project:save',(_event,value)=>{const safeItems=Array.isArray(value?.mediaItems)?value.mediaItems.filter(item=>item&&typeof item.path==='string'&&path.isAbsolute(item.path)&&pathRegistry.get(normalize(item.path))?.id===item.id):[];return project.save(app,{...value,mediaItems:safeItems})});
}
module.exports={registerMediaIpc,resolveMedia,registerAsset,getItem,getItems};
