const path=require('node:path');const fs=require('node:fs/promises');const ffmpeg=require('./ffmpeg.cjs');const {OpenAIProvider}=require('./ai/OpenAIProvider.cjs');const {AnalysisRepository}=require('./analysisRepository.cjs');
class AnalysisQueue{constructor(app,getItem,registerAsset){this.app=app;this.getItem=getItem;this.registerAsset=registerAsset;this.repo=new AnalysisRepository(app);this.pending=[];this.running=false;this.cancelled=new Set()}
 emit(sender,id,status,message,analysis){sender.send('analysis:progress',{mediaId:id,status,message,analysis})}
 enqueue(ids,sender){for(const id of ids)if(this.getItem(id)&&!this.pending.some(job=>job.id===id))this.pending.push({id,sender});void this.drain();return{queued:this.pending.length}}
 cancel(id){this.cancelled.add(id);this.pending=this.pending.filter(job=>job.id!==id)}
 async drain(){if(this.running)return;this.running=true;while(this.pending.length){const job=this.pending.shift();try{await this.process(job)}catch(error){console.error('[analysis] failed',job.id,error.message);this.emit(job.sender,job.id,'error',error.message)}}this.running=false}
 check(id){if(this.cancelled.delete(id))throw new Error('Analysis cancelled.')}
 async process({id,sender}){const item=this.getItem(id);if(!item)return;const started=Date.now();console.log('[analysis] started',id);const cached=await this.repo.load(item);if(cached){console.log('[analysis] cache hit',id);this.emit(sender,id,'ready','Analysis ready',cached);return}console.log('[analysis] cache miss',id);const root=path.join(this.app.getPath('cache'),'SavanaEdit'),analysis={mediaId:id,scenes:[],analyzedAt:new Date().toISOString(),version:1,stageErrors:{}};this.check(id);
 if(item.hasAudio){try{this.emit(sender,id,'extracting-audio','Extracting analysis audio…');analysis.audioPath=await ffmpeg.extractAudio(item.playbackPath||item.path,path.join(root,'audio',`${id}.wav`));analysis.waveform=await ffmpeg.waveform(item.playbackPath||item.path,path.join(root,'waveforms',`${id}.json`),id,item.duration);const settings=require('./settings.cjs');const config=await settings.load(this.app);this.emit(sender,id,'analyzing-audio','Detecting silence and loudness…');const measured=await ffmpeg.analyzeAudio(item.playbackPath||item.path,config.silenceThresholdDb,config.silenceMinimumSeconds);analysis.audio={hasAudio:true,sampleRate:item.audioSampleRate,channels:item.audioChannels,...measured,contentType:measured.silenceRanges.reduce((sum,x)=>sum+x.duration,0)>item.duration*.8?'silent':'unknown'};this.check(id);const provider=new OpenAIProvider();if(provider.configured()&&config.transcriptionProvider==='openai'){try{this.emit(sender,id,'transcribing','Transcribing speech…');analysis.transcript=await provider.transcribe({audioPath:analysis.audioPath,mediaId:id,duration:item.duration})}catch(error){analysis.stageErrors.transcript=error.message}}else analysis.stageErrors.transcript='Transcription provider is not configured.'}catch(error){analysis.stageErrors.audio=error.message}}else analysis.audio={hasAudio:false,silenceRanges:[],contentType:'silent'};
 this.check(id);try{this.emit(sender,id,'detecting-scenes','Detecting scene changes…');const config=await require('./settings.cjs').load(this.app),points=await ffmpeg.detectScenes(item.playbackPath||item.path,item.duration,config.sceneThreshold),sceneDir=path.join(root,'scenes',id);for(let index=0;index<points.length-1;index++){this.check(id);const start=points[index],end=points[index+1],sceneId=`${id}-s${index}`,thumbnailPath=path.join(sceneDir,`${index}.jpg`);try{await ffmpeg.thumbnailAt(item.playbackPath||item.path,start+(end-start)/2,thumbnailPath);this.registerAsset('scene',sceneId,thumbnailPath)}catch{}analysis.scenes.push({id:sceneId,mediaId:id,start,end,duration:end-start,thumbnailPath,index})}}catch(error){analysis.stageErrors.scenes=error.message}
 this.check(id);this.emit(sender,id,'summarizing','Creating clip summary…');const text=analysis.transcript?.fullText?.trim(),speech=Boolean(text),sceneCount=analysis.scenes.length;analysis.summary={summary:text?`${item.name} contains ${sceneCount} detected scene${sceneCount===1?'':'s'}. Spoken content: ${text.slice(0,300)}`:`${item.name} contains ${sceneCount} detected scene${sceneCount===1?'':'s'}${item.hasAudio?' with audio':' and no audio'}.`,topics:text?[...new Set(text.toLowerCase().match(/[a-z]{4,}/g)||[])].slice(0,12):[],contentType:speech?'spoken-video':item.hasAudio?'audio-visual':'silent-b-roll'};analysis.analyzedAt=new Date().toISOString();const saved=await this.repo.save(item,analysis);console.log('[analysis] finished',id,`${Date.now()-started}ms`);this.emit(sender,id,'ready','Analysis ready',saved)}
}
module.exports={AnalysisQueue};
