const {execFile}=require('node:child_process');const {promisify}=require('node:util');const fs=require('node:fs/promises');const path=require('node:path');const crypto=require('node:crypto');const run=promisify(execFile);const engine=require('./mediaEngine.cjs');
let electronApp;function configure(app){electronApp=app}async function binary(name){if(!electronApp)throw new Error('Media engine is not initialized.');return engine.resolve(electronApp,name)}function rate(value='0/1'){const[a,b]=value.split('/').map(Number),result=b?a/b:Number(value);return Number.isFinite(result)?result:0}
async function engineStatus(){return engine.status(electronApp)}async function probe(file){const exe=await binary('ffprobe');const{stdout}=await run(exe,['-v','error','-show_format','-show_streams','-of','json',file],{maxBuffer:12*1024*1024});return JSON.parse(stdout)}
async function analyze(file){const data=await probe(file),video=data.streams?.find(x=>x.codec_type==='video'),audio=data.streams?.find(x=>x.codec_type==='audio');if(!video)throw new Error('No usable video stream was found.');const stat=await fs.stat(file),duration=Number(data.format?.duration??video.duration??0);return{id:crypto.createHash('sha256').update(`${path.resolve(file).toLocaleLowerCase()}:${stat.size}`).digest('hex').slice(0,32),name:path.basename(file),path:path.resolve(file),duration:Number.isFinite(duration)?duration:0,width:Number(video.width||0),height:Number(video.height||0),fps:rate(video.avg_frame_rate||video.r_frame_rate),videoCodec:video.codec_name,audioCodec:audio?.codec_name,hasAudio:Boolean(audio),audioChannels:Number(audio?.channels||0)||undefined,audioSampleRate:Number(audio?.sample_rate||0)||undefined,fileSize:stat.size,createdAt:data.format?.tags?.creation_time||video.tags?.creation_time,status:'ready',analysisStatus:'not-analyzed'}}
async function callFfmpeg(args,options={}){const exe=await binary('ffmpeg');return run(exe,args,{maxBuffer:32*1024*1024,...options})}
async function thumbnail(file,duration,cacheDir,id){await fs.mkdir(cacheDir,{recursive:true});const output=path.join(cacheDir,`${id}.jpg`),seek=duration>2?duration*.2:Math.max(0,duration*.15);await callFfmpeg(['-y','-err_detect','ignore_err','-ss',String(seek),'-i',file,'-frames:v','1','-vf','scale=320:-2','-q:v','4',output]);return output}
async function thumbnailAt(file,time,output){await fs.mkdir(path.dirname(output),{recursive:true});await callFfmpeg(['-y','-ss',String(time),'-i',file,'-frames:v','1','-vf','scale=240:-2','-q:v','5',output]);return output}
async function salvage(source,cacheDir){await fs.mkdir(cacheDir,{recursive:true});const key=crypto.createHash('sha256').update(path.resolve(source).toLocaleLowerCase()).digest('hex').slice(0,32),output=path.join(cacheDir,`${key}.recovered.mkv`);await callFfmpeg(['-y','-fflags','+discardcorrupt+genpts','-err_detect','ignore_err','-i',source,'-map','0:v:0?','-map','0:a:0?','-c','copy','-max_interleave_delta','0',output]);return output}
async function previewProxy(source,cacheDir,id){await fs.mkdir(cacheDir,{recursive:true});const output=path.join(cacheDir,`${id}.preview.mp4`);try{await fs.access(output);return output}catch{}await callFfmpeg(['-y','-fflags','+discardcorrupt+genpts','-err_detect','ignore_err','-i',source,'-map','0:v:0','-map','0:a:0?','-c:v','libx264','-preset','veryfast','-crf','20','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',output]);return output}
async function extractAudio(source,output){try{await fs.access(output);return output}catch{}await fs.mkdir(path.dirname(output),{recursive:true});await callFfmpeg(['-y','-i',source,'-vn','-ac','1','-ar','16000','-c:a','pcm_s16le',output]);return output}
async function analyzeAudio(source,threshold=-35,minimum=.4){const{stderr}=await callFfmpeg(['-i',source,'-af',`silencedetect=noise=${threshold}dB:d=${minimum},volumedetect`,'-f','null','-']);const starts=[],ranges=[];for(const line of stderr.split(/\r?\n/)){let match=line.match(/silence_start:\s*([\d.]+)/);if(match)starts.push(Number(match[1]));match=line.match(/silence_end:\s*([\d.]+).*silence_duration:\s*([\d.]+)/);if(match)ranges.push({start:starts.shift()??Math.max(0,Number(match[1])-Number(match[2])),end:Number(match[1]),duration:Number(match[2])})}return{silenceRanges:ranges,averageDb:Number(stderr.match(/mean_volume:\s*(-?[\d.]+)/)?.[1]),peakDb:Number(stderr.match(/max_volume:\s*(-?[\d.]+)/)?.[1])}}
async function detectScenes(source,duration,threshold=.35){const{stderr}=await callFfmpeg(['-i',source,'-filter:v',`select=gt(scene\\,${threshold}),showinfo`,'-an','-f','null','-']);const points=[0,...[...stderr.matchAll(/pts_time:([\d.]+)/g)].map(x=>Number(x[1])).filter(x=>x>0&&x<duration),duration];return[...new Set(points)].sort((a,b)=>a-b)}
async function waveform(source,output,mediaId,duration){try{return JSON.parse(await fs.readFile(output,'utf8'))}catch{}await fs.mkdir(path.dirname(output),{recursive:true});const{stderr}=await callFfmpeg(['-i',source,'-vn','-af','asetnsamples=n=2048,astats=metadata=1:reset=1,ametadata=print:key=lavfi.astats.Overall.Peak_level','-f','null','-']);let peaks=[...stderr.matchAll(/lavfi\.astats\.Overall\.Peak_level=(-?[\d.]+)/g)].map(match=>Math.max(0,Math.min(1,Math.pow(10,Number(match[1])/20))));if(peaks.length>2000){const step=peaks.length/2000;peaks=Array.from({length:2000},(_,index)=>Math.max(...peaks.slice(Math.floor(index*step),Math.floor((index+1)*step))))}const data={mediaId,sampleCount:peaks.length,peaks,duration};await fs.writeFile(output,JSON.stringify(data),'utf8');return data}
module.exports={configure,engineStatus,analyze,thumbnail,thumbnailAt,salvage,previewProxy,extractAudio,analyzeAudio,detectScenes,waveform};
